config/routes.rb
# == Route Map
#
#                            Prefix Verb   URI Pattern                                       Controller#Action
#                   application_api        /                                                 ApplicationApi
#                     casein_videos GET    /casein/videos(.:format)                          casein/videos#index
#                                   POST   /casein/videos(.:format)                          casein/videos#create
#                  new_casein_video GET    /casein/videos/new(.:format)                      casein/videos#new
#                 edit_casein_video GET    /casein/videos/:id/edit(.:format)                 casein/videos#edit
#                      casein_video GET    /casein/videos/:id(.:format)                      casein/videos#show
#                                   PATCH  /casein/videos/:id(.:format)                      casein/videos#update
#                                   PUT    /casein/videos/:id(.:format)                      casein/videos#update
#                                   DELETE /casein/videos/:id(.:format)                      casein/videos#destroy
#            casein_monthly_reports GET    /casein/monthly_reports(.:format)                 casein/monthly_reports#index
#                                   POST   /casein/monthly_reports(.:format)                 casein/monthly_reports#create
#         new_casein_monthly_report GET    /casein/monthly_reports/new(.:format)             casein/monthly_reports#new
#        edit_casein_monthly_report GET    /casein/monthly_reports/:id/edit(.:format)        casein/monthly_reports#edit
#             casein_monthly_report GET    /casein/monthly_reports/:id(.:format)             casein/monthly_reports#show
#                                   PATCH  /casein/monthly_reports/:id(.:format)             casein/monthly_reports#update
#                                   PUT    /casein/monthly_reports/:id(.:format)             casein/monthly_reports#update
#                                   DELETE /casein/monthly_reports/:id(.:format)             casein/monthly_reports#destroy
#                      casein_gears GET    /casein/gears(.:format)                           casein/gears#index
#                                   POST   /casein/gears(.:format)                           casein/gears#create
#                   new_casein_gear GET    /casein/gears/new(.:format)                       casein/gears#new
#                  edit_casein_gear GET    /casein/gears/:id/edit(.:format)                  casein/gears#edit
#                       casein_gear GET    /casein/gears/:id(.:format)                       casein/gears#show
#                                   PATCH  /casein/gears/:id(.:format)                       casein/gears#update
#                                   PUT    /casein/gears/:id(.:format)                       casein/gears#update
#                                   DELETE /casein/gears/:id(.:format)                       casein/gears#destroy
#                  casein_car_gears GET    /casein/car_gears(.:format)                       casein/car_gears#index
#                                   POST   /casein/car_gears(.:format)                       casein/car_gears#create
#               new_casein_car_gear GET    /casein/car_gears/new(.:format)                   casein/car_gears#new
#              edit_casein_car_gear GET    /casein/car_gears/:id/edit(.:format)              casein/car_gears#edit
#                   casein_car_gear GET    /casein/car_gears/:id(.:format)                   casein/car_gears#show
#                                   PATCH  /casein/car_gears/:id(.:format)                   casein/car_gears#update
#                                   PUT    /casein/car_gears/:id(.:format)                   casein/car_gears#update
#                                   DELETE /casein/car_gears/:id(.:format)                   casein/car_gears#destroy
#                       casein_cars GET    /casein/cars(.:format)                            casein/cars#index
#                                   POST   /casein/cars(.:format)                            casein/cars#create
#                    new_casein_car GET    /casein/cars/new(.:format)                        casein/cars#new
#                   edit_casein_car GET    /casein/cars/:id/edit(.:format)                   casein/cars#edit
#                        casein_car GET    /casein/cars/:id(.:format)                        casein/cars#show
#                                   PATCH  /casein/cars/:id(.:format)                        casein/cars#update
#                                   PUT    /casein/cars/:id(.:format)                        casein/cars#update
#                                   DELETE /casein/cars/:id(.:format)                        casein/cars#destroy
#                     casein_brands GET    /casein/brands(.:format)                          casein/brands#index
#                                   POST   /casein/brands(.:format)                          casein/brands#create
#                  new_casein_brand GET    /casein/brands/new(.:format)                      casein/brands#new
#                 edit_casein_brand GET    /casein/brands/:id/edit(.:format)                 casein/brands#edit
#                      casein_brand GET    /casein/brands/:id(.:format)                      casein/brands#show
#                                   PATCH  /casein/brands/:id(.:format)                      casein/brands#update
#                                   PUT    /casein/brands/:id(.:format)                      casein/brands#update
#                                   DELETE /casein/brands/:id(.:format)                      casein/brands#destroy
#                   casein_articles GET    /casein/articles(.:format)                        casein/articles#index
#                                   POST   /casein/articles(.:format)                        casein/articles#create
#                new_casein_article GET    /casein/articles/new(.:format)                    casein/articles#new
#               edit_casein_article GET    /casein/articles/:id/edit(.:format)               casein/articles#edit
#                    casein_article GET    /casein/articles/:id(.:format)                    casein/articles#show
#                                   PATCH  /casein/articles/:id(.:format)                    casein/articles#update
#                                   PUT    /casein/articles/:id(.:format)                    casein/articles#update
#                                   DELETE /casein/articles/:id(.:format)                    casein/articles#destroy
#  upload_casein_vnexpress_crawlers GET    /casein/vnexpress_crawlers/upload(.:format)       casein/vnexpress_crawlers#upload
#                                   POST   /casein/vnexpress_crawlers/upload(.:format)       casein/vnexpress_crawlers#upload
#         casein_vnexpress_crawlers GET    /casein/vnexpress_crawlers(.:format)              casein/vnexpress_crawlers#index
#                             admin GET    /admin(.:format)                                  redirect(301, /casein)
# update_password_casein_admin_user PATCH  /casein/admin_users/:id/update_password(.:format) casein/admin_users#update_password
#  reset_password_casein_admin_user PATCH  /casein/admin_users/:id/reset_password(.:format)  casein/admin_users#reset_password
#                casein_admin_users GET    /casein/admin_users(.:format)                     casein/admin_users#index
#                                   POST   /casein/admin_users(.:format)                     casein/admin_users#create
#             new_casein_admin_user GET    /casein/admin_users/new(.:format)                 casein/admin_users#new
#            edit_casein_admin_user GET    /casein/admin_users/:id/edit(.:format)            casein/admin_users#edit
#                 casein_admin_user GET    /casein/admin_users/:id(.:format)                 casein/admin_users#show
#                                   PATCH  /casein/admin_users/:id(.:format)                 casein/admin_users#update
#                                   PUT    /casein/admin_users/:id(.:format)                 casein/admin_users#update
#                                   DELETE /casein/admin_users/:id(.:format)                 casein/admin_users#destroy
#     new_casein_admin_user_session GET    /casein/admin_user_session/new(.:format)          casein/admin_user_sessions#new
#         casein_admin_user_session DELETE /casein/admin_user_session(.:format)              casein/admin_user_sessions#destroy
#                                   POST   /casein/admin_user_session(.:format)              casein/admin_user_sessions#create
#        edit_casein_password_reset GET    /casein/password_reset/edit(.:format)             casein/password_resets#edit
#             casein_password_reset PATCH  /casein/password_reset(.:format)                  casein/password_resets#update
#                                   PUT    /casein/password_reset(.:format)                  casein/password_resets#update
#                                   POST   /casein/password_reset(.:format)                  casein/password_resets#create
#                      casein_blank GET    /casein/blank(.:format)                           casein/casein#blank
#                       casein_root GET    /casein(.:format)                                 casein/casein#index
#

Rails.application.routes.draw do
  # API
  mount ApplicationApi, at: '/'

  resources :infos, only: [:index]

  namespace :casein do
    resources :infos
    resources :notifications
    resources :car_groups
    resources :top_seller_car_monthlies
    resources :videos
    resources :monthly_reports
    resources :gears
    resources :car_gears
    resources :cars
    resources :brands
    resources :articles
    resources :vnexpress_crawlers, only: [:index] do
      collection do
        get :upload
        post :upload
      end
    end

app/controllers/casein/articles_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class ArticlesController < Casein::CaseinController
    before_action :fetch_article, only: %i[show update destroy edit]

    def index
      @casein_page_title = 'Articles'
      @articles = Article.order(sort_order(:id)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View article'
    end

    def new
      @casein_page_title = 'Add a new article'
      @article = Article.new
    end

    def edit
      @casein_page_title = 'Edit an article'
    end

    def create
      @article = Article.new article_params
      upload_image(@article, article_params)

      if @article.save
        flash[:notice] = 'Article created'
        redirect_to casein_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new article'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update article'

      upload_image(@article, article_params)

      if @article.update_attributes article_params
        flash[:notice] = 'Article has been updated'
        redirect_to casein_articles_path(@article)
      else
        flash.now[:warning] = 'There were problems when trying to update this article'
        render action: :show
      end
    end

    def destroy
      @article.destroy
      flash[:notice] = 'Article has been deleted'
      redirect_to casein_articles_path
    end

    private

    def article_params
      params.require(:article).permit(:name, :url, :image, :article_source_id, :article_type_id, :color_code, :status)
    end

    def fetch_article
      @article = Article.find params[:id]
    end

    def upload_image(article, article_params)
      if article_params['image']

        file = article_params['image']
        imgur_service = ImgurService.new({})
        img = imgur_service.upload_image(file)
        article.image_url = img.uploaded_image_link
        article.image_width = img.width
        article.image_height = img.height
        article
      end
    end
  end
end

app/controllers/casein/brands_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class BrandsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]

    def index
      @casein_page_title = 'Brands'
      @brands = Brand.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View brand'
      @brand = Brand.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new brand'
      @brand = Brand.new
    end

    def create
      @brand = Brand.new brand_params

      if @brand.save
        flash[:notice] = 'Brand created'
        redirect_to casein_brands_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new brand'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update brand'

      @brand = Brand.find params[:id]

      if @brand.update_attributes brand_params
        flash[:notice] = 'Brand has been updated'
        redirect_to casein_brands_path
      else
        flash.now[:warning] = 'There were problems when trying to update this brand'
        render action: :show
      end
    end

    def destroy
      @brand = Brand.find params[:id]

      @brand.destroy
      flash[:notice] = 'Brand has been deleted'
      redirect_to casein_brands_path
    end

    private

    def brand_params
      params.require(:brand).permit(:name, :desc)
    end
  end
end

app/controllers/casein/car_gears_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class CarGearsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]

    def index
      @casein_page_title = 'Car gears'
      @car_gears = CarGear.order(sort_order(:car_id)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View car gear'
      @car_gear = CarGear.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new car gear'
      @car_gear = CarGear.new
    end

    def create
      @car_gear = CarGear.new car_gear_params

      if @car_gear.save
        flash[:notice] = 'Car gear created'
        redirect_to casein_car_gears_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new car gear'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update car gear'

      @car_gear = CarGear.find params[:id]

      if @car_gear.update_attributes car_gear_params
        flash[:notice] = 'Car gear has been updated'
        redirect_to casein_car_gears_path
      else
        flash.now[:warning] = 'There were problems when trying to update this car gear'
        render action: :show
      end
    end

    def destroy
      @car_gear = CarGear.find params[:id]

      @car_gear.destroy
      flash[:notice] = 'Car gear has been deleted'
      redirect_to casein_car_gears_path
    end

    private

    def car_gear_params
      params.require(:car_gear).permit(:car_id, :gear_id, :desc)
    end
  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end

    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :casein, action: :blank
    end

    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end

    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

    # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end

    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
  end
end

app/views/casein/cars/_form.html.erb
<!-- Scaffolding generated by Casein v5.3.0.0 -->
<div class="row">
  <div class="col-lg-6">
    <label class="control-label" for="">Car Group</label>
    <div class="well">
      <%= f.select :car_group_id, CarGroup.all.map {|i| [i.name, i.id]}, { include_blank: true }, {class: 'form-control'} %>
    </div>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :name %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :dai_rong_cao %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :dung_tich_binh_xang %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :dong_co %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :cong_suat %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :momen_xoan %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :khoang_cach_gam %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :duong_kinh_vong_quay_toi_thieu %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :nguon_goc %>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :brand_id %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :hop_so %>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :so_cho %>
  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :muc_tieu_thu_nhien_lieu %>
  </div>
</div>

<div class="row">

  <div class="col-lg-6">
    <label class="control-label" for="">Report</label>
    <% year = Date.current.year %>
    <ul class="list-group">
      <% @car.monthly_reports.order(created_at: :desc).each do |report| %>
        <li class="list-group-item">
          <%= link_to report.time, casein_monthly_report_path(report.id) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/casein/cars/_search.html.erb
<%= search_form_for [:casein, @q], class: 'form-horizontal' do |f| %>
    <div class="form-group">
      <%= f.label :name_cont, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.search_field :name_cont, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :brand_id_eq, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.select :brand_id_eq, Brand.all.map{|i| [i.name, i.id]}, {}, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/casein/cars/_table.html.erb
<!-- Scaffolding generated by Casein v5.3.0.0 -->

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= casein_sort_link "Name", :name %></th>
      <th><%= casein_sort_link "Car group", :car_group_id %></th>
      <th><%= casein_sort_link "Dairongcao", :dai_rong_cao %></th>
      <th><%= casein_sort_link "Dungtichbinhxang", :dung_tich_binh_xang %></th>
      <th><%= casein_sort_link "Dongco", :dong_co %></th>
      <th><%= casein_sort_link "Brand", :brand %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <% cars.each do |car| %>
    <tr>
      <td><%= casein_table_cell_link car.name, casein_car_path(car) %></td>
      <td><%= casein_table_cell_link car.car_group&.name, casein_car_path(car) %></td>
      <td><%= casein_table_cell_link car.dai_rong_cao, casein_car_path(car) %></td>
      <td><%= casein_table_cell_link car.dung_tich_binh_xang, casein_car_path(car) %></td>
      <td><%= casein_table_cell_link car.dong_co, casein_car_path(car) %></td>
      <td><%= casein_table_cell_link car.brand.name, casein_car_path(car) %></td>
      <td>
        <%= link_to(casein_show_row_icon("trash"), casein_car_path(car), method: :delete, data: { confirm: "Are you sure you want to delete this car?" }) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/casein/cars/index.html.erb
<!-- Scaffolding generated by Casein v5.3.0.0 -->

<h2>Cars<%= casein_pagination_details @cars %></h2>

<%= render partial: 'casein/cars/search' %>
<%= render partial: 'casein/cars/table', locals: { cars: @cars } %>

<div class="text-center">
  <%= will_paginate @cars %>
</div>

<%= content_for :sidebar do %>

  <li><%= link_to "#{casein_show_icon "plus-sign"}Add a new car".html_safe, new_casein_car_path %></li>

<% end %>

app/views/casein/cars/new.html.erb
<!-- Scaffolding generated by Casein v5.3.0.0 -->

<h2>Add a new car</h2>

<%= form_for @car, url: casein_cars_path do |f| %>

  <%= render partial: 'casein/cars/form', locals: { f: f } %>

  <p class="submits">
    <%= link_to 'Cancel', casein_cars_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Add new car", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_cars_path %></li>
<% end %>

app/views/casein/cars/show.html.erb
<!-- Scaffolding generated by Casein v5.3.0.0 -->

<h2>View car</h2>

<%= form_for @car, url: casein_car_path(@car) do |f| %>

  <%= render partial: 'casein/cars/form', locals: { f: f } %>

  <p class="submits">
      <%= link_to 'Cancel', casein_cars_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Save changes", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_cars_path %></li>
<% end %>